version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=${DEV}
    ports:
      - "${PORT}:8000"
    volumes:
      - ./app:/app
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
  
  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  db-data:
